# K-meansを用いたクラスタリング

In [ ]:
from sklearn.cluster import KMeans
import numpy as np

inits= np.array([[-3.0],
                 [0]])
data = (np.array([[-2.7,-1.3,0.7,3.5,5.1]])).reshape(-1,1)
km = KMeans(n_clusters=2,init=inits, n_init=30, max_iter=300, tol=1e-04, random_state=0)
clusters_sklearn = km.fit_predict(data)

print(km.cluster_centers_)
print(km.labels_)

[[-2. ]
 [ 3.1]]
[0 0 1 1 1]


/usr/local/lib/python3.7/dist-packages/sklearn/cluster/_kmeans.py:1146: RuntimeWarning: Explicit initial center position passed: performing only one init in KMeans instead of n_init=30.
  self._check_params(X)


In [ ]:
from sklearn.cluster import KMeans
import numpy as np

inits= np.array([[-3.0],
                 [5.0]])
data = (np.array([[-2.7,-1.3,0.7,3.5,5.1]])).reshape(-1,1)
km = KMeans(n_clusters=2,init=inits, n_init=30, max_iter=300, tol=1e-04, random_state=0)
clusters_sklearn = km.fit_predict(data)
print(km.cluster_centers_)
print(km.labels_)

[[-1.1]
 [ 4.3]]
[0 0 0 1 1]


/usr/local/lib/python3.7/dist-packages/sklearn/cluster/_kmeans.py:1146: RuntimeWarning: Explicit initial center position passed: performing only one init in KMeans instead of n_init=30.
  self._check_params(X)


In [ ]:
from sklearn.cluster import KMeans
import numpy as np

inits= np.array([[-3.0],
                 [0.0],
                 [5.0]])
data = (np.array([[-2.7,-1.3,0.7,3.5,5.1]])).reshape(-1,1)
km = KMeans(n_clusters=3,init=inits, n_init=30, max_iter=300, tol=1e-04, random_state=0)
clusters_sklearn = km.fit_predict(data)

print(km.cluster_centers_)
print(km.labels_)

[[-2.7]
 [-0.3]
 [ 4.3]]
[0 1 1 2 2]


/usr/local/lib/python3.7/dist-packages/sklearn/cluster/_kmeans.py:1146: RuntimeWarning: Explicit initial center position passed: performing only one init in KMeans instead of n_init=30.
  self._check_params(X)
